version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - barcodes
  - barcodes
  - gotify
  - grocy
  - hass
  - postdata
  - printlabel
  - sonarjs
  - userentities
  - userentities
  - userfields
  - userobjects
ignoreWords: []
import: []
