export const BATTERY_CACHE_UPDATED = "BATTERY_CACHE_UPDATED";
export const CHORE_CACHE_UPDATED = "CHORE_CACHE_UPDATED";
export const TASK_CACHE_UPDATED = "TASK_CACHE_UPDATED";
export const GROCY_DATABASE_UPDATED = "GROCY_DATABASE_UPDATED";
